CHUCK_DIR=../src/

all: ckdl ckx

ckdl: ckdl.cpp
	gcc __CKDL_NO_BBQ__ -g -I$(CHUCK_DIR) ckdl.cpp $(CHUCK_DIR)chuck_dl.cpp -o ckdl -lstdc++

ckx: foo.ckx

foo.ckx: foo.cpp
	gcc -O3 -g -shared -I$(CHUCK_DIR) foo.cpp -o foo.ckx -lstdc++

clean:
	rm -f *~ ckdl.exe *.ckx
